[project]
name = "smart-cr"
version = "0.1.0"
description = "基于python的智能课程表管理与同步工具"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "requests>=2.34.2",
    "winrt-runtime>=2.0.0",
    "winrt-Windows.Data.Xml.Dom>=2.0.0",
    "winrt-Windows.UI.Notifications>=2.0.0",
]

[project.optional-dependencies]
winsdk = [
    "winsdk>=1.0.0b10",
]
